--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-rolling-update
  labels:
    app: rollingapp
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailabe: 1
      maxSurge: 1
  minReadySecond: 60
  selector:
    matchLabels:
      app: rollingapp
  template:
    metadata:
      name: deployment-pod-RU
      labels:
        app: rollingapp
    spec:
     containers:
     - name: dexios-container
       image: tendulkar999/spring-boot-mongo:5
       ports:
       - name: port
         containerPort: 8080
---


apiVersion: v1
kind: Service
metadata:
  name: deployment-rolling-update
  labels:
    app: rollingapp
spec:
  type: NodePort
  selector:
    app: rollingapp
  ports:
  - nodePort: 30456
    port: 80
    targetPort: 8080
