---
apiVersion: v1
kind: ReplicationController
metadata:
  name: springapp-rc
spec:
  replicas: 1
  selector:
    app: springapp
  template:
    metadata:
      name: spring-app-pod
      labels:
        app: springapp
    spec:
      containers:
      - image: tendulkar999/spring-boot-mongo:1
        name: springappcontainer
        ports:
        - name: springapp
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springapp-rc-service
  labels:
    app: springapp
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: springapp
  type: NodePort
  
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongorc
  labels:
    app: mongo
spec:
  replicas: 1
  template:
    metadata:
      name: mongo-pod
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        name: mongocontainer
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts: 
        - name : mongovolumemount
          mountPath: /data/db
      volumes:
      - name: mongovolumemount
        hostPath:
          path: /tmp/mongobkp 
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    name: mongo
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017


